# Generated by Django 6.0.4 on 2026-04-15 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='core.unit'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='core.unit'),
        ),
    ]
