# Generated by Django 6.0.4 on 2026-04-16 16:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_restaurant_delivery_fee_per_km_order_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_fee_per_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
