# Generated by Django 6.0.4 on 2026-04-18 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_transaction_created_by(apps, schema_editor):
    Transaction = apps.get_model("core", "Transaction")
    Order = apps.get_model("core", "Order")
    prefix = "Order payment — "
    for tx in Transaction.objects.filter(created_by__isnull=True, category="order_payment").iterator():
        remarks = tx.remarks or ""
        if not remarks.startswith(prefix):
            continue
        oid = remarks[len(prefix) :].strip()
        if not oid:
            continue
        waiter_id = (
            Order.objects.filter(restaurant_id=tx.restaurant_id, order_id=oid)
            .values_list("waiter_id", flat=True)
            .first()
        )
        if waiter_id:
            Transaction.objects.filter(pk=tx.pk).update(created_by_id=waiter_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_guest_customer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('transaction_fee', 'Transaction Fee'), ('order_payment', 'Order Payment'), ('subscription_fee', 'Subscription Fee'), ('sms_usage', 'SMS Usage'), ('share_distribution', 'Share Distribution'), ('share_withdrawal', 'Share Withdrawal'), ('due_paid', 'Due Paid'), ('ledger_credit', 'Ledger Credit'), ('ledger_debit', 'Ledger Debit'), ('salary', 'Salary')], max_length=40),
        ),
        migrations.RunPython(backfill_transaction_created_by, migrations.RunPython.noop),
    ]
