# Generated by Django 6.0.4 on 2026-04-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_bill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supersetting',
            name='due_payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='platform/due_qr/'),
        ),
    ]
