# Generated by Django 6.0.4 on 2026-05-14 21:40

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_restaurant_due_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulknotification',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storages.WebPImageStorage(), upload_to='notifications/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storages.WebPImageStorage(), upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='comboset',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storages.WebPImageStorage(), upload_to='combos/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, storage=core.storages.WebPImageStorage(), upload_to='order_bills/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storages.WebPImageStorage(), upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.storages.WebPImageStorage(), upload_to='restaurants/logos/'),
        ),
        migrations.AlterField(
            model_name='supersetting',
            name='due_payment_qr',
            field=models.ImageField(blank=True, null=True, storage=core.storages.WebPImageStorage(), upload_to='platform/due_qr/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storages.WebPImageStorage(), upload_to='suppliers/'),
        ),
        migrations.AlterField(
            model_name='table',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storages.WebPImageStorage(), upload_to='tables/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storages.WebPImageStorage(), upload_to='users/'),
        ),
    ]
