/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaiterMenuRouteImport } from './routes/waiter-menu'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ShareholderRouteImport } from './routes/shareholder'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as ShareholderIndexRouteImport } from './routes/shareholder.index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as SuperadminWithdrawalsRouteImport } from './routes/superadmin.withdrawals'
import { Route as SuperadminUsersRouteImport } from './routes/superadmin.users'
import { Route as SuperadminTransactionsRouteImport } from './routes/superadmin.transactions'
import { Route as SuperadminShareholdersRouteImport } from './routes/superadmin.shareholders'
import { Route as SuperadminSettingsRouteImport } from './routes/superadmin.settings'
import { Route as SuperadminRestaurantsRouteImport } from './routes/superadmin.restaurants'
import { Route as SuperadminProfileRouteImport } from './routes/superadmin.profile'
import { Route as SuperadminNotificationsRouteImport } from './routes/superadmin.notifications'
import { Route as StaffWaitingPickupRouteImport } from './routes/staff.waiting-pickup'
import { Route as StaffTransactionsRouteImport } from './routes/staff.transactions'
import { Route as StaffPurchasesRouteImport } from './routes/staff.purchases'
import { Route as StaffProfileRouteImport } from './routes/staff.profile'
import { Route as StaffPosRouteImport } from './routes/staff.pos'
import { Route as StaffPaymentAlertsRouteImport } from './routes/staff.payment-alerts'
import { Route as StaffNotificationsRouteImport } from './routes/staff.notifications'
import { Route as StaffMenuQrRouteImport } from './routes/staff.menu-qr'
import { Route as StaffLiveordersRouteImport } from './routes/staff.liveorders'
import { Route as StaffLedgerRouteImport } from './routes/staff.ledger'
import { Route as StaffExpensesRouteImport } from './routes/staff.expenses'
import { Route as StaffCashierRouteImport } from './routes/staff.cashier'
import { Route as ShareholderWithdrawalsRouteImport } from './routes/shareholder.withdrawals'
import { Route as ShareholderTransactionsRouteImport } from './routes/shareholder.transactions'
import { Route as ShareholderProfileRouteImport } from './routes/shareholder.profile'
import { Route as ShareholderNotificationsRouteImport } from './routes/shareholder.notifications'
import { Route as OwnerUsersRouteImport } from './routes/owner.users'
import { Route as OwnerUnitsRouteImport } from './routes/owner.units'
import { Route as OwnerTransactionsRouteImport } from './routes/owner.transactions'
import { Route as OwnerTablesRouteImport } from './routes/owner.tables'
import { Route as OwnerSuppliersRouteImport } from './routes/owner.suppliers'
import { Route as OwnerStocklogRouteImport } from './routes/owner.stocklog'
import { Route as OwnerStaffRouteImport } from './routes/owner.staff'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as OwnerRestaurantsRouteImport } from './routes/owner.restaurants'
import { Route as OwnerReportsRouteImport } from './routes/owner.reports'
import { Route as OwnerRawmaterialsRouteImport } from './routes/owner.rawmaterials'
import { Route as OwnerPurchasesRouteImport } from './routes/owner.purchases'
import { Route as OwnerProfileRouteImport } from './routes/owner.profile'
import { Route as OwnerProductsRouteImport } from './routes/owner.products'
import { Route as OwnerOrdersRouteImport } from './routes/owner.orders'
import { Route as OwnerNotificationsRouteImport } from './routes/owner.notifications'
import { Route as OwnerMenuQrRouteImport } from './routes/owner.menu-qr'
import { Route as OwnerLedgerRouteImport } from './routes/owner.ledger'
import { Route as OwnerExpensesRouteImport } from './routes/owner.expenses'
import { Route as OwnerCustomersRouteImport } from './routes/owner.customers'
import { Route as OwnerCombosRouteImport } from './routes/owner.combos'
import { Route as OwnerCategoriesRouteImport } from './routes/owner.categories'
import { Route as CustomerTransactionsRouteImport } from './routes/customer.transactions'
import { Route as CustomerRestaurantsRouteImport } from './routes/customer.restaurants'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerOrdersRouteImport } from './routes/customer.orders'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerLedgerRouteImport } from './routes/customer.ledger'
import { Route as CustomerCartRouteImport } from './routes/customer.cart'
import { Route as SuperadminWithdrawalsIdRouteImport } from './routes/superadmin.withdrawals_.$id'
import { Route as SuperadminUsersIdRouteImport } from './routes/superadmin.users_.$id'
import { Route as SuperadminTransactionsIdRouteImport } from './routes/superadmin.transactions_.$id'
import { Route as SuperadminShareholdersIdRouteImport } from './routes/superadmin.shareholders_.$id'
import { Route as SuperadminRestaurantsIdRouteImport } from './routes/superadmin.restaurants_.$id'
import { Route as SuperadminNotificationsIdRouteImport } from './routes/superadmin.notifications_.$id'
import { Route as StaffTransactionsIdRouteImport } from './routes/staff.transactions_.$id'
import { Route as StaffNotificationsIdRouteImport } from './routes/staff.notifications_.$id'
import { Route as StaffLedgerRestaurantIdRouteImport } from './routes/staff.ledger_.$restaurantId'
import { Route as ShareholderTransactionsIdRouteImport } from './routes/shareholder.transactions_.$id'
import { Route as OwnerTransactionsIdRouteImport } from './routes/owner.transactions_.$id'
import { Route as OwnerTablesIdRouteImport } from './routes/owner.tables_.$id'
import { Route as OwnerTablesAddRouteImport } from './routes/owner.tables.add'
import { Route as OwnerStocklogIdRouteImport } from './routes/owner.stocklog_.$id'
import { Route as OwnerStaffIdRouteImport } from './routes/owner.staff_.$id'
import { Route as OwnerStaffNewRouteImport } from './routes/owner.staff.new'
import { Route as OwnerRestaurantsRestaurantIdRouteImport } from './routes/owner.restaurants_.$restaurantId'
import { Route as OwnerRestaurantsNewRouteImport } from './routes/owner.restaurants.new'
import { Route as OwnerRestaurantsAddRouteImport } from './routes/owner.restaurants.add'
import { Route as OwnerRawmaterialsIdRouteImport } from './routes/owner.rawmaterials_.$id'
import { Route as OwnerPurchasesIdRouteImport } from './routes/owner.purchases_.$id'
import { Route as OwnerProductsNewRouteImport } from './routes/owner.products.new'
import { Route as OwnerProductsIdRouteImport } from './routes/owner.products.$id'
import { Route as OwnerOrdersIdRouteImport } from './routes/owner.orders_.$id'
import { Route as OwnerNotificationsIdRouteImport } from './routes/owner.notifications_.$id'
import { Route as OwnerExpensesIdRouteImport } from './routes/owner.expenses_.$id'
import { Route as OwnerCustomersIdRouteImport } from './routes/owner.customers_.$id'
import { Route as OwnerCombosIdRouteImport } from './routes/owner.combos.$id'
import { Route as CustomerLedgerRestaurantIdRouteImport } from './routes/customer.ledger_.$restaurantId'
import { Route as StaffLedgerPartyTypePartyIdRouteImport } from './routes/staff.ledger_.$partyType.$partyId'
import { Route as OwnerTablesIdEditRouteImport } from './routes/owner.tables_.$id.edit'
import { Route as OwnerStaffIdEditRouteImport } from './routes/owner.staff_.$id.edit'
import { Route as OwnerProductsIdEditRouteImport } from './routes/owner.products.$id.edit'
import { Route as OwnerLedgerPartyTypePartyIdRouteImport } from './routes/owner.ledger_.$partyType.$partyId'
import { Route as CustomerLedgerPartyTypePartyIdRouteImport } from './routes/customer.ledger_.$partyType.$partyId'

const WaiterMenuRoute = WaiterMenuRouteImport.update({
  id: '/waiter-menu',
  path: '/waiter-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareholderRoute = ShareholderRouteImport.update({
  id: '/shareholder',
  path: '/shareholder',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const ShareholderIndexRoute = ShareholderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShareholderRoute,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const SuperadminWithdrawalsRoute = SuperadminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminUsersRoute = SuperadminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminTransactionsRoute = SuperadminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminShareholdersRoute = SuperadminShareholdersRouteImport.update({
  id: '/shareholders',
  path: '/shareholders',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSettingsRoute = SuperadminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminRestaurantsRoute = SuperadminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminProfileRoute = SuperadminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminNotificationsRoute = SuperadminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SuperadminRoute,
} as any)
const StaffWaitingPickupRoute = StaffWaitingPickupRouteImport.update({
  id: '/waiting-pickup',
  path: '/waiting-pickup',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTransactionsRoute = StaffTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPurchasesRoute = StaffPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPosRoute = StaffPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPaymentAlertsRoute = StaffPaymentAlertsRouteImport.update({
  id: '/payment-alerts',
  path: '/payment-alerts',
  getParentRoute: () => StaffRoute,
} as any)
const StaffNotificationsRoute = StaffNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMenuQrRoute = StaffMenuQrRouteImport.update({
  id: '/menu-qr',
  path: '/menu-qr',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLiveordersRoute = StaffLiveordersRouteImport.update({
  id: '/liveorders',
  path: '/liveorders',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLedgerRoute = StaffLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => StaffRoute,
} as any)
const StaffExpensesRoute = StaffExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCashierRoute = StaffCashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => StaffRoute,
} as any)
const ShareholderWithdrawalsRoute = ShareholderWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => ShareholderRoute,
} as any)
const ShareholderTransactionsRoute = ShareholderTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ShareholderRoute,
} as any)
const ShareholderProfileRoute = ShareholderProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShareholderRoute,
} as any)
const ShareholderNotificationsRoute =
  ShareholderNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ShareholderRoute,
  } as any)
const OwnerUsersRoute = OwnerUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerUnitsRoute = OwnerUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerTransactionsRoute = OwnerTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerTablesRoute = OwnerTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSuppliersRoute = OwnerSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerStocklogRoute = OwnerStocklogRouteImport.update({
  id: '/stocklog',
  path: '/stocklog',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerStaffRoute = OwnerStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerRestaurantsRoute = OwnerRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerReportsRoute = OwnerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerRawmaterialsRoute = OwnerRawmaterialsRouteImport.update({
  id: '/rawmaterials',
  path: '/rawmaterials',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPurchasesRoute = OwnerPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerProfileRoute = OwnerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerProductsRoute = OwnerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOrdersRoute = OwnerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerNotificationsRoute = OwnerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMenuQrRoute = OwnerMenuQrRouteImport.update({
  id: '/menu-qr',
  path: '/menu-qr',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerLedgerRoute = OwnerLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerExpensesRoute = OwnerExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCustomersRoute = OwnerCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCombosRoute = OwnerCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCategoriesRoute = OwnerCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => OwnerRoute,
} as any)
const CustomerTransactionsRoute = CustomerTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerRestaurantsRoute = CustomerRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerLedgerRoute = CustomerLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CustomerRoute,
} as any)
const SuperadminWithdrawalsIdRoute = SuperadminWithdrawalsIdRouteImport.update({
  id: '/withdrawals_/$id',
  path: '/withdrawals/$id',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminUsersIdRoute = SuperadminUsersIdRouteImport.update({
  id: '/users_/$id',
  path: '/users/$id',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminTransactionsIdRoute =
  SuperadminTransactionsIdRouteImport.update({
    id: '/transactions_/$id',
    path: '/transactions/$id',
    getParentRoute: () => SuperadminRoute,
  } as any)
const SuperadminShareholdersIdRoute =
  SuperadminShareholdersIdRouteImport.update({
    id: '/shareholders_/$id',
    path: '/shareholders/$id',
    getParentRoute: () => SuperadminRoute,
  } as any)
const SuperadminRestaurantsIdRoute = SuperadminRestaurantsIdRouteImport.update({
  id: '/restaurants_/$id',
  path: '/restaurants/$id',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminNotificationsIdRoute =
  SuperadminNotificationsIdRouteImport.update({
    id: '/notifications_/$id',
    path: '/notifications/$id',
    getParentRoute: () => SuperadminRoute,
  } as any)
const StaffTransactionsIdRoute = StaffTransactionsIdRouteImport.update({
  id: '/transactions_/$id',
  path: '/transactions/$id',
  getParentRoute: () => StaffRoute,
} as any)
const StaffNotificationsIdRoute = StaffNotificationsIdRouteImport.update({
  id: '/notifications_/$id',
  path: '/notifications/$id',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLedgerRestaurantIdRoute = StaffLedgerRestaurantIdRouteImport.update({
  id: '/ledger_/$restaurantId',
  path: '/ledger/$restaurantId',
  getParentRoute: () => StaffRoute,
} as any)
const ShareholderTransactionsIdRoute =
  ShareholderTransactionsIdRouteImport.update({
    id: '/transactions_/$id',
    path: '/transactions/$id',
    getParentRoute: () => ShareholderRoute,
  } as any)
const OwnerTransactionsIdRoute = OwnerTransactionsIdRouteImport.update({
  id: '/transactions_/$id',
  path: '/transactions/$id',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerTablesIdRoute = OwnerTablesIdRouteImport.update({
  id: '/tables_/$id',
  path: '/tables/$id',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerTablesAddRoute = OwnerTablesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => OwnerTablesRoute,
} as any)
const OwnerStocklogIdRoute = OwnerStocklogIdRouteImport.update({
  id: '/stocklog_/$id',
  path: '/stocklog/$id',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerStaffIdRoute = OwnerStaffIdRouteImport.update({
  id: '/staff_/$id',
  path: '/staff/$id',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerStaffNewRoute = OwnerStaffNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OwnerStaffRoute,
} as any)
const OwnerRestaurantsRestaurantIdRoute =
  OwnerRestaurantsRestaurantIdRouteImport.update({
    id: '/restaurants_/$restaurantId',
    path: '/restaurants/$restaurantId',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerRestaurantsNewRoute = OwnerRestaurantsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OwnerRestaurantsRoute,
} as any)
const OwnerRestaurantsAddRoute = OwnerRestaurantsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => OwnerRestaurantsRoute,
} as any)
const OwnerRawmaterialsIdRoute = OwnerRawmaterialsIdRouteImport.update({
  id: '/rawmaterials_/$id',
  path: '/rawmaterials/$id',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPurchasesIdRoute = OwnerPurchasesIdRouteImport.update({
  id: '/purchases_/$id',
  path: '/purchases/$id',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerProductsNewRoute = OwnerProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OwnerProductsRoute,
} as any)
const OwnerProductsIdRoute = OwnerProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OwnerProductsRoute,
} as any)
const OwnerOrdersIdRoute = OwnerOrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerNotificationsIdRoute = OwnerNotificationsIdRouteImport.update({
  id: '/notifications_/$id',
  path: '/notifications/$id',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerExpensesIdRoute = OwnerExpensesIdRouteImport.update({
  id: '/expenses_/$id',
  path: '/expenses/$id',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCustomersIdRoute = OwnerCustomersIdRouteImport.update({
  id: '/customers_/$id',
  path: '/customers/$id',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCombosIdRoute = OwnerCombosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OwnerCombosRoute,
} as any)
const CustomerLedgerRestaurantIdRoute =
  CustomerLedgerRestaurantIdRouteImport.update({
    id: '/ledger_/$restaurantId',
    path: '/ledger/$restaurantId',
    getParentRoute: () => CustomerRoute,
  } as any)
const StaffLedgerPartyTypePartyIdRoute =
  StaffLedgerPartyTypePartyIdRouteImport.update({
    id: '/ledger_/$partyType/$partyId',
    path: '/ledger/$partyType/$partyId',
    getParentRoute: () => StaffRoute,
  } as any)
const OwnerTablesIdEditRoute = OwnerTablesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => OwnerTablesIdRoute,
} as any)
const OwnerStaffIdEditRoute = OwnerStaffIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => OwnerStaffIdRoute,
} as any)
const OwnerProductsIdEditRoute = OwnerProductsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => OwnerProductsIdRoute,
} as any)
const OwnerLedgerPartyTypePartyIdRoute =
  OwnerLedgerPartyTypePartyIdRouteImport.update({
    id: '/ledger_/$partyType/$partyId',
    path: '/ledger/$partyType/$partyId',
    getParentRoute: () => OwnerRoute,
  } as any)
const CustomerLedgerPartyTypePartyIdRoute =
  CustomerLedgerPartyTypePartyIdRouteImport.update({
    id: '/ledger_/$partyType/$partyId',
    path: '/ledger/$partyType/$partyId',
    getParentRoute: () => CustomerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/shareholder': typeof ShareholderRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/superadmin': typeof SuperadminRouteWithChildren
  '/waiter-menu': typeof WaiterMenuRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/ledger': typeof CustomerLedgerRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/restaurants': typeof CustomerRestaurantsRoute
  '/customer/transactions': typeof CustomerTransactionsRoute
  '/owner/categories': typeof OwnerCategoriesRoute
  '/owner/combos': typeof OwnerCombosRouteWithChildren
  '/owner/customers': typeof OwnerCustomersRoute
  '/owner/expenses': typeof OwnerExpensesRoute
  '/owner/ledger': typeof OwnerLedgerRoute
  '/owner/menu-qr': typeof OwnerMenuQrRoute
  '/owner/notifications': typeof OwnerNotificationsRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/products': typeof OwnerProductsRouteWithChildren
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/purchases': typeof OwnerPurchasesRoute
  '/owner/rawmaterials': typeof OwnerRawmaterialsRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/restaurants': typeof OwnerRestaurantsRouteWithChildren
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/staff': typeof OwnerStaffRouteWithChildren
  '/owner/stocklog': typeof OwnerStocklogRoute
  '/owner/suppliers': typeof OwnerSuppliersRoute
  '/owner/tables': typeof OwnerTablesRouteWithChildren
  '/owner/transactions': typeof OwnerTransactionsRoute
  '/owner/units': typeof OwnerUnitsRoute
  '/owner/users': typeof OwnerUsersRoute
  '/shareholder/notifications': typeof ShareholderNotificationsRoute
  '/shareholder/profile': typeof ShareholderProfileRoute
  '/shareholder/transactions': typeof ShareholderTransactionsRoute
  '/shareholder/withdrawals': typeof ShareholderWithdrawalsRoute
  '/staff/cashier': typeof StaffCashierRoute
  '/staff/expenses': typeof StaffExpensesRoute
  '/staff/ledger': typeof StaffLedgerRoute
  '/staff/liveorders': typeof StaffLiveordersRoute
  '/staff/menu-qr': typeof StaffMenuQrRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/payment-alerts': typeof StaffPaymentAlertsRoute
  '/staff/pos': typeof StaffPosRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/purchases': typeof StaffPurchasesRoute
  '/staff/transactions': typeof StaffTransactionsRoute
  '/staff/waiting-pickup': typeof StaffWaitingPickupRoute
  '/superadmin/notifications': typeof SuperadminNotificationsRoute
  '/superadmin/profile': typeof SuperadminProfileRoute
  '/superadmin/restaurants': typeof SuperadminRestaurantsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/shareholders': typeof SuperadminShareholdersRoute
  '/superadmin/transactions': typeof SuperadminTransactionsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/superadmin/withdrawals': typeof SuperadminWithdrawalsRoute
  '/customer/': typeof CustomerIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/shareholder/': typeof ShareholderIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/customer/ledger/$restaurantId': typeof CustomerLedgerRestaurantIdRoute
  '/owner/combos/$id': typeof OwnerCombosIdRoute
  '/owner/customers/$id': typeof OwnerCustomersIdRoute
  '/owner/expenses/$id': typeof OwnerExpensesIdRoute
  '/owner/notifications/$id': typeof OwnerNotificationsIdRoute
  '/owner/orders/$id': typeof OwnerOrdersIdRoute
  '/owner/products/$id': typeof OwnerProductsIdRouteWithChildren
  '/owner/products/new': typeof OwnerProductsNewRoute
  '/owner/purchases/$id': typeof OwnerPurchasesIdRoute
  '/owner/rawmaterials/$id': typeof OwnerRawmaterialsIdRoute
  '/owner/restaurants/add': typeof OwnerRestaurantsAddRoute
  '/owner/restaurants/new': typeof OwnerRestaurantsNewRoute
  '/owner/restaurants/$restaurantId': typeof OwnerRestaurantsRestaurantIdRoute
  '/owner/staff/new': typeof OwnerStaffNewRoute
  '/owner/staff/$id': typeof OwnerStaffIdRouteWithChildren
  '/owner/stocklog/$id': typeof OwnerStocklogIdRoute
  '/owner/tables/add': typeof OwnerTablesAddRoute
  '/owner/tables/$id': typeof OwnerTablesIdRouteWithChildren
  '/owner/transactions/$id': typeof OwnerTransactionsIdRoute
  '/shareholder/transactions/$id': typeof ShareholderTransactionsIdRoute
  '/staff/ledger/$restaurantId': typeof StaffLedgerRestaurantIdRoute
  '/staff/notifications/$id': typeof StaffNotificationsIdRoute
  '/staff/transactions/$id': typeof StaffTransactionsIdRoute
  '/superadmin/notifications/$id': typeof SuperadminNotificationsIdRoute
  '/superadmin/restaurants/$id': typeof SuperadminRestaurantsIdRoute
  '/superadmin/shareholders/$id': typeof SuperadminShareholdersIdRoute
  '/superadmin/transactions/$id': typeof SuperadminTransactionsIdRoute
  '/superadmin/users/$id': typeof SuperadminUsersIdRoute
  '/superadmin/withdrawals/$id': typeof SuperadminWithdrawalsIdRoute
  '/customer/ledger/$partyType/$partyId': typeof CustomerLedgerPartyTypePartyIdRoute
  '/owner/ledger/$partyType/$partyId': typeof OwnerLedgerPartyTypePartyIdRoute
  '/owner/products/$id/edit': typeof OwnerProductsIdEditRoute
  '/owner/staff/$id/edit': typeof OwnerStaffIdEditRoute
  '/owner/tables/$id/edit': typeof OwnerTablesIdEditRoute
  '/staff/ledger/$partyType/$partyId': typeof StaffLedgerPartyTypePartyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/waiter-menu': typeof WaiterMenuRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/ledger': typeof CustomerLedgerRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/restaurants': typeof CustomerRestaurantsRoute
  '/customer/transactions': typeof CustomerTransactionsRoute
  '/owner/categories': typeof OwnerCategoriesRoute
  '/owner/combos': typeof OwnerCombosRouteWithChildren
  '/owner/customers': typeof OwnerCustomersRoute
  '/owner/expenses': typeof OwnerExpensesRoute
  '/owner/ledger': typeof OwnerLedgerRoute
  '/owner/menu-qr': typeof OwnerMenuQrRoute
  '/owner/notifications': typeof OwnerNotificationsRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/products': typeof OwnerProductsRouteWithChildren
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/purchases': typeof OwnerPurchasesRoute
  '/owner/rawmaterials': typeof OwnerRawmaterialsRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/restaurants': typeof OwnerRestaurantsRouteWithChildren
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/staff': typeof OwnerStaffRouteWithChildren
  '/owner/stocklog': typeof OwnerStocklogRoute
  '/owner/suppliers': typeof OwnerSuppliersRoute
  '/owner/tables': typeof OwnerTablesRouteWithChildren
  '/owner/transactions': typeof OwnerTransactionsRoute
  '/owner/units': typeof OwnerUnitsRoute
  '/owner/users': typeof OwnerUsersRoute
  '/shareholder/notifications': typeof ShareholderNotificationsRoute
  '/shareholder/profile': typeof ShareholderProfileRoute
  '/shareholder/transactions': typeof ShareholderTransactionsRoute
  '/shareholder/withdrawals': typeof ShareholderWithdrawalsRoute
  '/staff/cashier': typeof StaffCashierRoute
  '/staff/expenses': typeof StaffExpensesRoute
  '/staff/ledger': typeof StaffLedgerRoute
  '/staff/liveorders': typeof StaffLiveordersRoute
  '/staff/menu-qr': typeof StaffMenuQrRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/payment-alerts': typeof StaffPaymentAlertsRoute
  '/staff/pos': typeof StaffPosRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/purchases': typeof StaffPurchasesRoute
  '/staff/transactions': typeof StaffTransactionsRoute
  '/staff/waiting-pickup': typeof StaffWaitingPickupRoute
  '/superadmin/notifications': typeof SuperadminNotificationsRoute
  '/superadmin/profile': typeof SuperadminProfileRoute
  '/superadmin/restaurants': typeof SuperadminRestaurantsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/shareholders': typeof SuperadminShareholdersRoute
  '/superadmin/transactions': typeof SuperadminTransactionsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/superadmin/withdrawals': typeof SuperadminWithdrawalsRoute
  '/customer': typeof CustomerIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/shareholder': typeof ShareholderIndexRoute
  '/staff': typeof StaffIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/customer/ledger/$restaurantId': typeof CustomerLedgerRestaurantIdRoute
  '/owner/combos/$id': typeof OwnerCombosIdRoute
  '/owner/customers/$id': typeof OwnerCustomersIdRoute
  '/owner/expenses/$id': typeof OwnerExpensesIdRoute
  '/owner/notifications/$id': typeof OwnerNotificationsIdRoute
  '/owner/orders/$id': typeof OwnerOrdersIdRoute
  '/owner/products/$id': typeof OwnerProductsIdRouteWithChildren
  '/owner/products/new': typeof OwnerProductsNewRoute
  '/owner/purchases/$id': typeof OwnerPurchasesIdRoute
  '/owner/rawmaterials/$id': typeof OwnerRawmaterialsIdRoute
  '/owner/restaurants/add': typeof OwnerRestaurantsAddRoute
  '/owner/restaurants/new': typeof OwnerRestaurantsNewRoute
  '/owner/restaurants/$restaurantId': typeof OwnerRestaurantsRestaurantIdRoute
  '/owner/staff/new': typeof OwnerStaffNewRoute
  '/owner/staff/$id': typeof OwnerStaffIdRouteWithChildren
  '/owner/stocklog/$id': typeof OwnerStocklogIdRoute
  '/owner/tables/add': typeof OwnerTablesAddRoute
  '/owner/tables/$id': typeof OwnerTablesIdRouteWithChildren
  '/owner/transactions/$id': typeof OwnerTransactionsIdRoute
  '/shareholder/transactions/$id': typeof ShareholderTransactionsIdRoute
  '/staff/ledger/$restaurantId': typeof StaffLedgerRestaurantIdRoute
  '/staff/notifications/$id': typeof StaffNotificationsIdRoute
  '/staff/transactions/$id': typeof StaffTransactionsIdRoute
  '/superadmin/notifications/$id': typeof SuperadminNotificationsIdRoute
  '/superadmin/restaurants/$id': typeof SuperadminRestaurantsIdRoute
  '/superadmin/shareholders/$id': typeof SuperadminShareholdersIdRoute
  '/superadmin/transactions/$id': typeof SuperadminTransactionsIdRoute
  '/superadmin/users/$id': typeof SuperadminUsersIdRoute
  '/superadmin/withdrawals/$id': typeof SuperadminWithdrawalsIdRoute
  '/customer/ledger/$partyType/$partyId': typeof CustomerLedgerPartyTypePartyIdRoute
  '/owner/ledger/$partyType/$partyId': typeof OwnerLedgerPartyTypePartyIdRoute
  '/owner/products/$id/edit': typeof OwnerProductsIdEditRoute
  '/owner/staff/$id/edit': typeof OwnerStaffIdEditRoute
  '/owner/tables/$id/edit': typeof OwnerTablesIdEditRoute
  '/staff/ledger/$partyType/$partyId': typeof StaffLedgerPartyTypePartyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/shareholder': typeof ShareholderRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/superadmin': typeof SuperadminRouteWithChildren
  '/waiter-menu': typeof WaiterMenuRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/ledger': typeof CustomerLedgerRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/restaurants': typeof CustomerRestaurantsRoute
  '/customer/transactions': typeof CustomerTransactionsRoute
  '/owner/categories': typeof OwnerCategoriesRoute
  '/owner/combos': typeof OwnerCombosRouteWithChildren
  '/owner/customers': typeof OwnerCustomersRoute
  '/owner/expenses': typeof OwnerExpensesRoute
  '/owner/ledger': typeof OwnerLedgerRoute
  '/owner/menu-qr': typeof OwnerMenuQrRoute
  '/owner/notifications': typeof OwnerNotificationsRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/products': typeof OwnerProductsRouteWithChildren
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/purchases': typeof OwnerPurchasesRoute
  '/owner/rawmaterials': typeof OwnerRawmaterialsRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/restaurants': typeof OwnerRestaurantsRouteWithChildren
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/staff': typeof OwnerStaffRouteWithChildren
  '/owner/stocklog': typeof OwnerStocklogRoute
  '/owner/suppliers': typeof OwnerSuppliersRoute
  '/owner/tables': typeof OwnerTablesRouteWithChildren
  '/owner/transactions': typeof OwnerTransactionsRoute
  '/owner/units': typeof OwnerUnitsRoute
  '/owner/users': typeof OwnerUsersRoute
  '/shareholder/notifications': typeof ShareholderNotificationsRoute
  '/shareholder/profile': typeof ShareholderProfileRoute
  '/shareholder/transactions': typeof ShareholderTransactionsRoute
  '/shareholder/withdrawals': typeof ShareholderWithdrawalsRoute
  '/staff/cashier': typeof StaffCashierRoute
  '/staff/expenses': typeof StaffExpensesRoute
  '/staff/ledger': typeof StaffLedgerRoute
  '/staff/liveorders': typeof StaffLiveordersRoute
  '/staff/menu-qr': typeof StaffMenuQrRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/payment-alerts': typeof StaffPaymentAlertsRoute
  '/staff/pos': typeof StaffPosRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/purchases': typeof StaffPurchasesRoute
  '/staff/transactions': typeof StaffTransactionsRoute
  '/staff/waiting-pickup': typeof StaffWaitingPickupRoute
  '/superadmin/notifications': typeof SuperadminNotificationsRoute
  '/superadmin/profile': typeof SuperadminProfileRoute
  '/superadmin/restaurants': typeof SuperadminRestaurantsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/shareholders': typeof SuperadminShareholdersRoute
  '/superadmin/transactions': typeof SuperadminTransactionsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/superadmin/withdrawals': typeof SuperadminWithdrawalsRoute
  '/customer/': typeof CustomerIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/shareholder/': typeof ShareholderIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/customer/ledger_/$restaurantId': typeof CustomerLedgerRestaurantIdRoute
  '/owner/combos/$id': typeof OwnerCombosIdRoute
  '/owner/customers_/$id': typeof OwnerCustomersIdRoute
  '/owner/expenses_/$id': typeof OwnerExpensesIdRoute
  '/owner/notifications_/$id': typeof OwnerNotificationsIdRoute
  '/owner/orders_/$id': typeof OwnerOrdersIdRoute
  '/owner/products/$id': typeof OwnerProductsIdRouteWithChildren
  '/owner/products/new': typeof OwnerProductsNewRoute
  '/owner/purchases_/$id': typeof OwnerPurchasesIdRoute
  '/owner/rawmaterials_/$id': typeof OwnerRawmaterialsIdRoute
  '/owner/restaurants/add': typeof OwnerRestaurantsAddRoute
  '/owner/restaurants/new': typeof OwnerRestaurantsNewRoute
  '/owner/restaurants_/$restaurantId': typeof OwnerRestaurantsRestaurantIdRoute
  '/owner/staff/new': typeof OwnerStaffNewRoute
  '/owner/staff_/$id': typeof OwnerStaffIdRouteWithChildren
  '/owner/stocklog_/$id': typeof OwnerStocklogIdRoute
  '/owner/tables/add': typeof OwnerTablesAddRoute
  '/owner/tables_/$id': typeof OwnerTablesIdRouteWithChildren
  '/owner/transactions_/$id': typeof OwnerTransactionsIdRoute
  '/shareholder/transactions_/$id': typeof ShareholderTransactionsIdRoute
  '/staff/ledger_/$restaurantId': typeof StaffLedgerRestaurantIdRoute
  '/staff/notifications_/$id': typeof StaffNotificationsIdRoute
  '/staff/transactions_/$id': typeof StaffTransactionsIdRoute
  '/superadmin/notifications_/$id': typeof SuperadminNotificationsIdRoute
  '/superadmin/restaurants_/$id': typeof SuperadminRestaurantsIdRoute
  '/superadmin/shareholders_/$id': typeof SuperadminShareholdersIdRoute
  '/superadmin/transactions_/$id': typeof SuperadminTransactionsIdRoute
  '/superadmin/users_/$id': typeof SuperadminUsersIdRoute
  '/superadmin/withdrawals_/$id': typeof SuperadminWithdrawalsIdRoute
  '/customer/ledger_/$partyType/$partyId': typeof CustomerLedgerPartyTypePartyIdRoute
  '/owner/ledger_/$partyType/$partyId': typeof OwnerLedgerPartyTypePartyIdRoute
  '/owner/products/$id/edit': typeof OwnerProductsIdEditRoute
  '/owner/staff_/$id/edit': typeof OwnerStaffIdEditRoute
  '/owner/tables_/$id/edit': typeof OwnerTablesIdEditRoute
  '/staff/ledger_/$partyType/$partyId': typeof StaffLedgerPartyTypePartyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/dashboard'
    | '/login'
    | '/owner'
    | '/register'
    | '/shareholder'
    | '/staff'
    | '/superadmin'
    | '/waiter-menu'
    | '/customer/cart'
    | '/customer/ledger'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/customer/restaurants'
    | '/customer/transactions'
    | '/owner/categories'
    | '/owner/combos'
    | '/owner/customers'
    | '/owner/expenses'
    | '/owner/ledger'
    | '/owner/menu-qr'
    | '/owner/notifications'
    | '/owner/orders'
    | '/owner/products'
    | '/owner/profile'
    | '/owner/purchases'
    | '/owner/rawmaterials'
    | '/owner/reports'
    | '/owner/restaurants'
    | '/owner/settings'
    | '/owner/staff'
    | '/owner/stocklog'
    | '/owner/suppliers'
    | '/owner/tables'
    | '/owner/transactions'
    | '/owner/units'
    | '/owner/users'
    | '/shareholder/notifications'
    | '/shareholder/profile'
    | '/shareholder/transactions'
    | '/shareholder/withdrawals'
    | '/staff/cashier'
    | '/staff/expenses'
    | '/staff/ledger'
    | '/staff/liveorders'
    | '/staff/menu-qr'
    | '/staff/notifications'
    | '/staff/payment-alerts'
    | '/staff/pos'
    | '/staff/profile'
    | '/staff/purchases'
    | '/staff/transactions'
    | '/staff/waiting-pickup'
    | '/superadmin/notifications'
    | '/superadmin/profile'
    | '/superadmin/restaurants'
    | '/superadmin/settings'
    | '/superadmin/shareholders'
    | '/superadmin/transactions'
    | '/superadmin/users'
    | '/superadmin/withdrawals'
    | '/customer/'
    | '/owner/'
    | '/shareholder/'
    | '/staff/'
    | '/superadmin/'
    | '/customer/ledger/$restaurantId'
    | '/owner/combos/$id'
    | '/owner/customers/$id'
    | '/owner/expenses/$id'
    | '/owner/notifications/$id'
    | '/owner/orders/$id'
    | '/owner/products/$id'
    | '/owner/products/new'
    | '/owner/purchases/$id'
    | '/owner/rawmaterials/$id'
    | '/owner/restaurants/add'
    | '/owner/restaurants/new'
    | '/owner/restaurants/$restaurantId'
    | '/owner/staff/new'
    | '/owner/staff/$id'
    | '/owner/stocklog/$id'
    | '/owner/tables/add'
    | '/owner/tables/$id'
    | '/owner/transactions/$id'
    | '/shareholder/transactions/$id'
    | '/staff/ledger/$restaurantId'
    | '/staff/notifications/$id'
    | '/staff/transactions/$id'
    | '/superadmin/notifications/$id'
    | '/superadmin/restaurants/$id'
    | '/superadmin/shareholders/$id'
    | '/superadmin/transactions/$id'
    | '/superadmin/users/$id'
    | '/superadmin/withdrawals/$id'
    | '/customer/ledger/$partyType/$partyId'
    | '/owner/ledger/$partyType/$partyId'
    | '/owner/products/$id/edit'
    | '/owner/staff/$id/edit'
    | '/owner/tables/$id/edit'
    | '/staff/ledger/$partyType/$partyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/waiter-menu'
    | '/customer/cart'
    | '/customer/ledger'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/customer/restaurants'
    | '/customer/transactions'
    | '/owner/categories'
    | '/owner/combos'
    | '/owner/customers'
    | '/owner/expenses'
    | '/owner/ledger'
    | '/owner/menu-qr'
    | '/owner/notifications'
    | '/owner/orders'
    | '/owner/products'
    | '/owner/profile'
    | '/owner/purchases'
    | '/owner/rawmaterials'
    | '/owner/reports'
    | '/owner/restaurants'
    | '/owner/settings'
    | '/owner/staff'
    | '/owner/stocklog'
    | '/owner/suppliers'
    | '/owner/tables'
    | '/owner/transactions'
    | '/owner/units'
    | '/owner/users'
    | '/shareholder/notifications'
    | '/shareholder/profile'
    | '/shareholder/transactions'
    | '/shareholder/withdrawals'
    | '/staff/cashier'
    | '/staff/expenses'
    | '/staff/ledger'
    | '/staff/liveorders'
    | '/staff/menu-qr'
    | '/staff/notifications'
    | '/staff/payment-alerts'
    | '/staff/pos'
    | '/staff/profile'
    | '/staff/purchases'
    | '/staff/transactions'
    | '/staff/waiting-pickup'
    | '/superadmin/notifications'
    | '/superadmin/profile'
    | '/superadmin/restaurants'
    | '/superadmin/settings'
    | '/superadmin/shareholders'
    | '/superadmin/transactions'
    | '/superadmin/users'
    | '/superadmin/withdrawals'
    | '/customer'
    | '/owner'
    | '/shareholder'
    | '/staff'
    | '/superadmin'
    | '/customer/ledger/$restaurantId'
    | '/owner/combos/$id'
    | '/owner/customers/$id'
    | '/owner/expenses/$id'
    | '/owner/notifications/$id'
    | '/owner/orders/$id'
    | '/owner/products/$id'
    | '/owner/products/new'
    | '/owner/purchases/$id'
    | '/owner/rawmaterials/$id'
    | '/owner/restaurants/add'
    | '/owner/restaurants/new'
    | '/owner/restaurants/$restaurantId'
    | '/owner/staff/new'
    | '/owner/staff/$id'
    | '/owner/stocklog/$id'
    | '/owner/tables/add'
    | '/owner/tables/$id'
    | '/owner/transactions/$id'
    | '/shareholder/transactions/$id'
    | '/staff/ledger/$restaurantId'
    | '/staff/notifications/$id'
    | '/staff/transactions/$id'
    | '/superadmin/notifications/$id'
    | '/superadmin/restaurants/$id'
    | '/superadmin/shareholders/$id'
    | '/superadmin/transactions/$id'
    | '/superadmin/users/$id'
    | '/superadmin/withdrawals/$id'
    | '/customer/ledger/$partyType/$partyId'
    | '/owner/ledger/$partyType/$partyId'
    | '/owner/products/$id/edit'
    | '/owner/staff/$id/edit'
    | '/owner/tables/$id/edit'
    | '/staff/ledger/$partyType/$partyId'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/dashboard'
    | '/login'
    | '/owner'
    | '/register'
    | '/shareholder'
    | '/staff'
    | '/superadmin'
    | '/waiter-menu'
    | '/customer/cart'
    | '/customer/ledger'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/customer/restaurants'
    | '/customer/transactions'
    | '/owner/categories'
    | '/owner/combos'
    | '/owner/customers'
    | '/owner/expenses'
    | '/owner/ledger'
    | '/owner/menu-qr'
    | '/owner/notifications'
    | '/owner/orders'
    | '/owner/products'
    | '/owner/profile'
    | '/owner/purchases'
    | '/owner/rawmaterials'
    | '/owner/reports'
    | '/owner/restaurants'
    | '/owner/settings'
    | '/owner/staff'
    | '/owner/stocklog'
    | '/owner/suppliers'
    | '/owner/tables'
    | '/owner/transactions'
    | '/owner/units'
    | '/owner/users'
    | '/shareholder/notifications'
    | '/shareholder/profile'
    | '/shareholder/transactions'
    | '/shareholder/withdrawals'
    | '/staff/cashier'
    | '/staff/expenses'
    | '/staff/ledger'
    | '/staff/liveorders'
    | '/staff/menu-qr'
    | '/staff/notifications'
    | '/staff/payment-alerts'
    | '/staff/pos'
    | '/staff/profile'
    | '/staff/purchases'
    | '/staff/transactions'
    | '/staff/waiting-pickup'
    | '/superadmin/notifications'
    | '/superadmin/profile'
    | '/superadmin/restaurants'
    | '/superadmin/settings'
    | '/superadmin/shareholders'
    | '/superadmin/transactions'
    | '/superadmin/users'
    | '/superadmin/withdrawals'
    | '/customer/'
    | '/owner/'
    | '/shareholder/'
    | '/staff/'
    | '/superadmin/'
    | '/customer/ledger_/$restaurantId'
    | '/owner/combos/$id'
    | '/owner/customers_/$id'
    | '/owner/expenses_/$id'
    | '/owner/notifications_/$id'
    | '/owner/orders_/$id'
    | '/owner/products/$id'
    | '/owner/products/new'
    | '/owner/purchases_/$id'
    | '/owner/rawmaterials_/$id'
    | '/owner/restaurants/add'
    | '/owner/restaurants/new'
    | '/owner/restaurants_/$restaurantId'
    | '/owner/staff/new'
    | '/owner/staff_/$id'
    | '/owner/stocklog_/$id'
    | '/owner/tables/add'
    | '/owner/tables_/$id'
    | '/owner/transactions_/$id'
    | '/shareholder/transactions_/$id'
    | '/staff/ledger_/$restaurantId'
    | '/staff/notifications_/$id'
    | '/staff/transactions_/$id'
    | '/superadmin/notifications_/$id'
    | '/superadmin/restaurants_/$id'
    | '/superadmin/shareholders_/$id'
    | '/superadmin/transactions_/$id'
    | '/superadmin/users_/$id'
    | '/superadmin/withdrawals_/$id'
    | '/customer/ledger_/$partyType/$partyId'
    | '/owner/ledger_/$partyType/$partyId'
    | '/owner/products/$id/edit'
    | '/owner/staff_/$id/edit'
    | '/owner/tables_/$id/edit'
    | '/staff/ledger_/$partyType/$partyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ShareholderRoute: typeof ShareholderRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  SuperadminRoute: typeof SuperadminRouteWithChildren
  WaiterMenuRoute: typeof WaiterMenuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiter-menu': {
      id: '/waiter-menu'
      path: '/waiter-menu'
      fullPath: '/waiter-menu'
      preLoaderRoute: typeof WaiterMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholder': {
      id: '/shareholder'
      path: '/shareholder'
      fullPath: '/shareholder'
      preLoaderRoute: typeof ShareholderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/shareholder/': {
      id: '/shareholder/'
      path: '/'
      fullPath: '/shareholder/'
      preLoaderRoute: typeof ShareholderIndexRouteImport
      parentRoute: typeof ShareholderRoute
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/superadmin/withdrawals': {
      id: '/superadmin/withdrawals'
      path: '/withdrawals'
      fullPath: '/superadmin/withdrawals'
      preLoaderRoute: typeof SuperadminWithdrawalsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/users': {
      id: '/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof SuperadminUsersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/transactions': {
      id: '/superadmin/transactions'
      path: '/transactions'
      fullPath: '/superadmin/transactions'
      preLoaderRoute: typeof SuperadminTransactionsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/shareholders': {
      id: '/superadmin/shareholders'
      path: '/shareholders'
      fullPath: '/superadmin/shareholders'
      preLoaderRoute: typeof SuperadminShareholdersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/settings': {
      id: '/superadmin/settings'
      path: '/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof SuperadminSettingsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/restaurants': {
      id: '/superadmin/restaurants'
      path: '/restaurants'
      fullPath: '/superadmin/restaurants'
      preLoaderRoute: typeof SuperadminRestaurantsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/profile': {
      id: '/superadmin/profile'
      path: '/profile'
      fullPath: '/superadmin/profile'
      preLoaderRoute: typeof SuperadminProfileRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/notifications': {
      id: '/superadmin/notifications'
      path: '/notifications'
      fullPath: '/superadmin/notifications'
      preLoaderRoute: typeof SuperadminNotificationsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/staff/waiting-pickup': {
      id: '/staff/waiting-pickup'
      path: '/waiting-pickup'
      fullPath: '/staff/waiting-pickup'
      preLoaderRoute: typeof StaffWaitingPickupRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/transactions': {
      id: '/staff/transactions'
      path: '/transactions'
      fullPath: '/staff/transactions'
      preLoaderRoute: typeof StaffTransactionsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/purchases': {
      id: '/staff/purchases'
      path: '/purchases'
      fullPath: '/staff/purchases'
      preLoaderRoute: typeof StaffPurchasesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/pos': {
      id: '/staff/pos'
      path: '/pos'
      fullPath: '/staff/pos'
      preLoaderRoute: typeof StaffPosRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/payment-alerts': {
      id: '/staff/payment-alerts'
      path: '/payment-alerts'
      fullPath: '/staff/payment-alerts'
      preLoaderRoute: typeof StaffPaymentAlertsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/notifications': {
      id: '/staff/notifications'
      path: '/notifications'
      fullPath: '/staff/notifications'
      preLoaderRoute: typeof StaffNotificationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/menu-qr': {
      id: '/staff/menu-qr'
      path: '/menu-qr'
      fullPath: '/staff/menu-qr'
      preLoaderRoute: typeof StaffMenuQrRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/liveorders': {
      id: '/staff/liveorders'
      path: '/liveorders'
      fullPath: '/staff/liveorders'
      preLoaderRoute: typeof StaffLiveordersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/ledger': {
      id: '/staff/ledger'
      path: '/ledger'
      fullPath: '/staff/ledger'
      preLoaderRoute: typeof StaffLedgerRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/expenses': {
      id: '/staff/expenses'
      path: '/expenses'
      fullPath: '/staff/expenses'
      preLoaderRoute: typeof StaffExpensesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/cashier': {
      id: '/staff/cashier'
      path: '/cashier'
      fullPath: '/staff/cashier'
      preLoaderRoute: typeof StaffCashierRouteImport
      parentRoute: typeof StaffRoute
    }
    '/shareholder/withdrawals': {
      id: '/shareholder/withdrawals'
      path: '/withdrawals'
      fullPath: '/shareholder/withdrawals'
      preLoaderRoute: typeof ShareholderWithdrawalsRouteImport
      parentRoute: typeof ShareholderRoute
    }
    '/shareholder/transactions': {
      id: '/shareholder/transactions'
      path: '/transactions'
      fullPath: '/shareholder/transactions'
      preLoaderRoute: typeof ShareholderTransactionsRouteImport
      parentRoute: typeof ShareholderRoute
    }
    '/shareholder/profile': {
      id: '/shareholder/profile'
      path: '/profile'
      fullPath: '/shareholder/profile'
      preLoaderRoute: typeof ShareholderProfileRouteImport
      parentRoute: typeof ShareholderRoute
    }
    '/shareholder/notifications': {
      id: '/shareholder/notifications'
      path: '/notifications'
      fullPath: '/shareholder/notifications'
      preLoaderRoute: typeof ShareholderNotificationsRouteImport
      parentRoute: typeof ShareholderRoute
    }
    '/owner/users': {
      id: '/owner/users'
      path: '/users'
      fullPath: '/owner/users'
      preLoaderRoute: typeof OwnerUsersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/units': {
      id: '/owner/units'
      path: '/units'
      fullPath: '/owner/units'
      preLoaderRoute: typeof OwnerUnitsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/transactions': {
      id: '/owner/transactions'
      path: '/transactions'
      fullPath: '/owner/transactions'
      preLoaderRoute: typeof OwnerTransactionsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/tables': {
      id: '/owner/tables'
      path: '/tables'
      fullPath: '/owner/tables'
      preLoaderRoute: typeof OwnerTablesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/suppliers': {
      id: '/owner/suppliers'
      path: '/suppliers'
      fullPath: '/owner/suppliers'
      preLoaderRoute: typeof OwnerSuppliersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/stocklog': {
      id: '/owner/stocklog'
      path: '/stocklog'
      fullPath: '/owner/stocklog'
      preLoaderRoute: typeof OwnerStocklogRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/staff': {
      id: '/owner/staff'
      path: '/staff'
      fullPath: '/owner/staff'
      preLoaderRoute: typeof OwnerStaffRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/restaurants': {
      id: '/owner/restaurants'
      path: '/restaurants'
      fullPath: '/owner/restaurants'
      preLoaderRoute: typeof OwnerRestaurantsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/reports': {
      id: '/owner/reports'
      path: '/reports'
      fullPath: '/owner/reports'
      preLoaderRoute: typeof OwnerReportsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/rawmaterials': {
      id: '/owner/rawmaterials'
      path: '/rawmaterials'
      fullPath: '/owner/rawmaterials'
      preLoaderRoute: typeof OwnerRawmaterialsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/purchases': {
      id: '/owner/purchases'
      path: '/purchases'
      fullPath: '/owner/purchases'
      preLoaderRoute: typeof OwnerPurchasesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/profile': {
      id: '/owner/profile'
      path: '/profile'
      fullPath: '/owner/profile'
      preLoaderRoute: typeof OwnerProfileRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/products': {
      id: '/owner/products'
      path: '/products'
      fullPath: '/owner/products'
      preLoaderRoute: typeof OwnerProductsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/orders': {
      id: '/owner/orders'
      path: '/orders'
      fullPath: '/owner/orders'
      preLoaderRoute: typeof OwnerOrdersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/notifications': {
      id: '/owner/notifications'
      path: '/notifications'
      fullPath: '/owner/notifications'
      preLoaderRoute: typeof OwnerNotificationsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/menu-qr': {
      id: '/owner/menu-qr'
      path: '/menu-qr'
      fullPath: '/owner/menu-qr'
      preLoaderRoute: typeof OwnerMenuQrRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/ledger': {
      id: '/owner/ledger'
      path: '/ledger'
      fullPath: '/owner/ledger'
      preLoaderRoute: typeof OwnerLedgerRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/expenses': {
      id: '/owner/expenses'
      path: '/expenses'
      fullPath: '/owner/expenses'
      preLoaderRoute: typeof OwnerExpensesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/customers': {
      id: '/owner/customers'
      path: '/customers'
      fullPath: '/owner/customers'
      preLoaderRoute: typeof OwnerCustomersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/combos': {
      id: '/owner/combos'
      path: '/combos'
      fullPath: '/owner/combos'
      preLoaderRoute: typeof OwnerCombosRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/categories': {
      id: '/owner/categories'
      path: '/categories'
      fullPath: '/owner/categories'
      preLoaderRoute: typeof OwnerCategoriesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/customer/transactions': {
      id: '/customer/transactions'
      path: '/transactions'
      fullPath: '/customer/transactions'
      preLoaderRoute: typeof CustomerTransactionsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/restaurants': {
      id: '/customer/restaurants'
      path: '/restaurants'
      fullPath: '/customer/restaurants'
      preLoaderRoute: typeof CustomerRestaurantsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/orders': {
      id: '/customer/orders'
      path: '/orders'
      fullPath: '/customer/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/ledger': {
      id: '/customer/ledger'
      path: '/ledger'
      fullPath: '/customer/ledger'
      preLoaderRoute: typeof CustomerLedgerRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/cart': {
      id: '/customer/cart'
      path: '/cart'
      fullPath: '/customer/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/superadmin/withdrawals_/$id': {
      id: '/superadmin/withdrawals_/$id'
      path: '/withdrawals/$id'
      fullPath: '/superadmin/withdrawals/$id'
      preLoaderRoute: typeof SuperadminWithdrawalsIdRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/users_/$id': {
      id: '/superadmin/users_/$id'
      path: '/users/$id'
      fullPath: '/superadmin/users/$id'
      preLoaderRoute: typeof SuperadminUsersIdRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/transactions_/$id': {
      id: '/superadmin/transactions_/$id'
      path: '/transactions/$id'
      fullPath: '/superadmin/transactions/$id'
      preLoaderRoute: typeof SuperadminTransactionsIdRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/shareholders_/$id': {
      id: '/superadmin/shareholders_/$id'
      path: '/shareholders/$id'
      fullPath: '/superadmin/shareholders/$id'
      preLoaderRoute: typeof SuperadminShareholdersIdRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/restaurants_/$id': {
      id: '/superadmin/restaurants_/$id'
      path: '/restaurants/$id'
      fullPath: '/superadmin/restaurants/$id'
      preLoaderRoute: typeof SuperadminRestaurantsIdRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/notifications_/$id': {
      id: '/superadmin/notifications_/$id'
      path: '/notifications/$id'
      fullPath: '/superadmin/notifications/$id'
      preLoaderRoute: typeof SuperadminNotificationsIdRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/staff/transactions_/$id': {
      id: '/staff/transactions_/$id'
      path: '/transactions/$id'
      fullPath: '/staff/transactions/$id'
      preLoaderRoute: typeof StaffTransactionsIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/notifications_/$id': {
      id: '/staff/notifications_/$id'
      path: '/notifications/$id'
      fullPath: '/staff/notifications/$id'
      preLoaderRoute: typeof StaffNotificationsIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/ledger_/$restaurantId': {
      id: '/staff/ledger_/$restaurantId'
      path: '/ledger/$restaurantId'
      fullPath: '/staff/ledger/$restaurantId'
      preLoaderRoute: typeof StaffLedgerRestaurantIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/shareholder/transactions_/$id': {
      id: '/shareholder/transactions_/$id'
      path: '/transactions/$id'
      fullPath: '/shareholder/transactions/$id'
      preLoaderRoute: typeof ShareholderTransactionsIdRouteImport
      parentRoute: typeof ShareholderRoute
    }
    '/owner/transactions_/$id': {
      id: '/owner/transactions_/$id'
      path: '/transactions/$id'
      fullPath: '/owner/transactions/$id'
      preLoaderRoute: typeof OwnerTransactionsIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/tables_/$id': {
      id: '/owner/tables_/$id'
      path: '/tables/$id'
      fullPath: '/owner/tables/$id'
      preLoaderRoute: typeof OwnerTablesIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/tables/add': {
      id: '/owner/tables/add'
      path: '/add'
      fullPath: '/owner/tables/add'
      preLoaderRoute: typeof OwnerTablesAddRouteImport
      parentRoute: typeof OwnerTablesRoute
    }
    '/owner/stocklog_/$id': {
      id: '/owner/stocklog_/$id'
      path: '/stocklog/$id'
      fullPath: '/owner/stocklog/$id'
      preLoaderRoute: typeof OwnerStocklogIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/staff_/$id': {
      id: '/owner/staff_/$id'
      path: '/staff/$id'
      fullPath: '/owner/staff/$id'
      preLoaderRoute: typeof OwnerStaffIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/staff/new': {
      id: '/owner/staff/new'
      path: '/new'
      fullPath: '/owner/staff/new'
      preLoaderRoute: typeof OwnerStaffNewRouteImport
      parentRoute: typeof OwnerStaffRoute
    }
    '/owner/restaurants_/$restaurantId': {
      id: '/owner/restaurants_/$restaurantId'
      path: '/restaurants/$restaurantId'
      fullPath: '/owner/restaurants/$restaurantId'
      preLoaderRoute: typeof OwnerRestaurantsRestaurantIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/restaurants/new': {
      id: '/owner/restaurants/new'
      path: '/new'
      fullPath: '/owner/restaurants/new'
      preLoaderRoute: typeof OwnerRestaurantsNewRouteImport
      parentRoute: typeof OwnerRestaurantsRoute
    }
    '/owner/restaurants/add': {
      id: '/owner/restaurants/add'
      path: '/add'
      fullPath: '/owner/restaurants/add'
      preLoaderRoute: typeof OwnerRestaurantsAddRouteImport
      parentRoute: typeof OwnerRestaurantsRoute
    }
    '/owner/rawmaterials_/$id': {
      id: '/owner/rawmaterials_/$id'
      path: '/rawmaterials/$id'
      fullPath: '/owner/rawmaterials/$id'
      preLoaderRoute: typeof OwnerRawmaterialsIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/purchases_/$id': {
      id: '/owner/purchases_/$id'
      path: '/purchases/$id'
      fullPath: '/owner/purchases/$id'
      preLoaderRoute: typeof OwnerPurchasesIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/products/new': {
      id: '/owner/products/new'
      path: '/new'
      fullPath: '/owner/products/new'
      preLoaderRoute: typeof OwnerProductsNewRouteImport
      parentRoute: typeof OwnerProductsRoute
    }
    '/owner/products/$id': {
      id: '/owner/products/$id'
      path: '/$id'
      fullPath: '/owner/products/$id'
      preLoaderRoute: typeof OwnerProductsIdRouteImport
      parentRoute: typeof OwnerProductsRoute
    }
    '/owner/orders_/$id': {
      id: '/owner/orders_/$id'
      path: '/orders/$id'
      fullPath: '/owner/orders/$id'
      preLoaderRoute: typeof OwnerOrdersIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/notifications_/$id': {
      id: '/owner/notifications_/$id'
      path: '/notifications/$id'
      fullPath: '/owner/notifications/$id'
      preLoaderRoute: typeof OwnerNotificationsIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/expenses_/$id': {
      id: '/owner/expenses_/$id'
      path: '/expenses/$id'
      fullPath: '/owner/expenses/$id'
      preLoaderRoute: typeof OwnerExpensesIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/customers_/$id': {
      id: '/owner/customers_/$id'
      path: '/customers/$id'
      fullPath: '/owner/customers/$id'
      preLoaderRoute: typeof OwnerCustomersIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/combos/$id': {
      id: '/owner/combos/$id'
      path: '/$id'
      fullPath: '/owner/combos/$id'
      preLoaderRoute: typeof OwnerCombosIdRouteImport
      parentRoute: typeof OwnerCombosRoute
    }
    '/customer/ledger_/$restaurantId': {
      id: '/customer/ledger_/$restaurantId'
      path: '/ledger/$restaurantId'
      fullPath: '/customer/ledger/$restaurantId'
      preLoaderRoute: typeof CustomerLedgerRestaurantIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/staff/ledger_/$partyType/$partyId': {
      id: '/staff/ledger_/$partyType/$partyId'
      path: '/ledger/$partyType/$partyId'
      fullPath: '/staff/ledger/$partyType/$partyId'
      preLoaderRoute: typeof StaffLedgerPartyTypePartyIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/owner/tables_/$id/edit': {
      id: '/owner/tables_/$id/edit'
      path: '/edit'
      fullPath: '/owner/tables/$id/edit'
      preLoaderRoute: typeof OwnerTablesIdEditRouteImport
      parentRoute: typeof OwnerTablesIdRoute
    }
    '/owner/staff_/$id/edit': {
      id: '/owner/staff_/$id/edit'
      path: '/edit'
      fullPath: '/owner/staff/$id/edit'
      preLoaderRoute: typeof OwnerStaffIdEditRouteImport
      parentRoute: typeof OwnerStaffIdRoute
    }
    '/owner/products/$id/edit': {
      id: '/owner/products/$id/edit'
      path: '/edit'
      fullPath: '/owner/products/$id/edit'
      preLoaderRoute: typeof OwnerProductsIdEditRouteImport
      parentRoute: typeof OwnerProductsIdRoute
    }
    '/owner/ledger_/$partyType/$partyId': {
      id: '/owner/ledger_/$partyType/$partyId'
      path: '/ledger/$partyType/$partyId'
      fullPath: '/owner/ledger/$partyType/$partyId'
      preLoaderRoute: typeof OwnerLedgerPartyTypePartyIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/customer/ledger_/$partyType/$partyId': {
      id: '/customer/ledger_/$partyType/$partyId'
      path: '/ledger/$partyType/$partyId'
      fullPath: '/customer/ledger/$partyType/$partyId'
      preLoaderRoute: typeof CustomerLedgerPartyTypePartyIdRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface CustomerRouteChildren {
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerLedgerRoute: typeof CustomerLedgerRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerRestaurantsRoute: typeof CustomerRestaurantsRoute
  CustomerTransactionsRoute: typeof CustomerTransactionsRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerLedgerRestaurantIdRoute: typeof CustomerLedgerRestaurantIdRoute
  CustomerLedgerPartyTypePartyIdRoute: typeof CustomerLedgerPartyTypePartyIdRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerCartRoute: CustomerCartRoute,
  CustomerLedgerRoute: CustomerLedgerRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerRestaurantsRoute: CustomerRestaurantsRoute,
  CustomerTransactionsRoute: CustomerTransactionsRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerLedgerRestaurantIdRoute: CustomerLedgerRestaurantIdRoute,
  CustomerLedgerPartyTypePartyIdRoute: CustomerLedgerPartyTypePartyIdRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface OwnerCombosRouteChildren {
  OwnerCombosIdRoute: typeof OwnerCombosIdRoute
}

const OwnerCombosRouteChildren: OwnerCombosRouteChildren = {
  OwnerCombosIdRoute: OwnerCombosIdRoute,
}

const OwnerCombosRouteWithChildren = OwnerCombosRoute._addFileChildren(
  OwnerCombosRouteChildren,
)

interface OwnerProductsIdRouteChildren {
  OwnerProductsIdEditRoute: typeof OwnerProductsIdEditRoute
}

const OwnerProductsIdRouteChildren: OwnerProductsIdRouteChildren = {
  OwnerProductsIdEditRoute: OwnerProductsIdEditRoute,
}

const OwnerProductsIdRouteWithChildren = OwnerProductsIdRoute._addFileChildren(
  OwnerProductsIdRouteChildren,
)

interface OwnerProductsRouteChildren {
  OwnerProductsIdRoute: typeof OwnerProductsIdRouteWithChildren
  OwnerProductsNewRoute: typeof OwnerProductsNewRoute
}

const OwnerProductsRouteChildren: OwnerProductsRouteChildren = {
  OwnerProductsIdRoute: OwnerProductsIdRouteWithChildren,
  OwnerProductsNewRoute: OwnerProductsNewRoute,
}

const OwnerProductsRouteWithChildren = OwnerProductsRoute._addFileChildren(
  OwnerProductsRouteChildren,
)

interface OwnerRestaurantsRouteChildren {
  OwnerRestaurantsAddRoute: typeof OwnerRestaurantsAddRoute
  OwnerRestaurantsNewRoute: typeof OwnerRestaurantsNewRoute
}

const OwnerRestaurantsRouteChildren: OwnerRestaurantsRouteChildren = {
  OwnerRestaurantsAddRoute: OwnerRestaurantsAddRoute,
  OwnerRestaurantsNewRoute: OwnerRestaurantsNewRoute,
}

const OwnerRestaurantsRouteWithChildren =
  OwnerRestaurantsRoute._addFileChildren(OwnerRestaurantsRouteChildren)

interface OwnerStaffRouteChildren {
  OwnerStaffNewRoute: typeof OwnerStaffNewRoute
}

const OwnerStaffRouteChildren: OwnerStaffRouteChildren = {
  OwnerStaffNewRoute: OwnerStaffNewRoute,
}

const OwnerStaffRouteWithChildren = OwnerStaffRoute._addFileChildren(
  OwnerStaffRouteChildren,
)

interface OwnerTablesRouteChildren {
  OwnerTablesAddRoute: typeof OwnerTablesAddRoute
}

const OwnerTablesRouteChildren: OwnerTablesRouteChildren = {
  OwnerTablesAddRoute: OwnerTablesAddRoute,
}

const OwnerTablesRouteWithChildren = OwnerTablesRoute._addFileChildren(
  OwnerTablesRouteChildren,
)

interface OwnerStaffIdRouteChildren {
  OwnerStaffIdEditRoute: typeof OwnerStaffIdEditRoute
}

const OwnerStaffIdRouteChildren: OwnerStaffIdRouteChildren = {
  OwnerStaffIdEditRoute: OwnerStaffIdEditRoute,
}

const OwnerStaffIdRouteWithChildren = OwnerStaffIdRoute._addFileChildren(
  OwnerStaffIdRouteChildren,
)

interface OwnerTablesIdRouteChildren {
  OwnerTablesIdEditRoute: typeof OwnerTablesIdEditRoute
}

const OwnerTablesIdRouteChildren: OwnerTablesIdRouteChildren = {
  OwnerTablesIdEditRoute: OwnerTablesIdEditRoute,
}

const OwnerTablesIdRouteWithChildren = OwnerTablesIdRoute._addFileChildren(
  OwnerTablesIdRouteChildren,
)

interface OwnerRouteChildren {
  OwnerCategoriesRoute: typeof OwnerCategoriesRoute
  OwnerCombosRoute: typeof OwnerCombosRouteWithChildren
  OwnerCustomersRoute: typeof OwnerCustomersRoute
  OwnerExpensesRoute: typeof OwnerExpensesRoute
  OwnerLedgerRoute: typeof OwnerLedgerRoute
  OwnerMenuQrRoute: typeof OwnerMenuQrRoute
  OwnerNotificationsRoute: typeof OwnerNotificationsRoute
  OwnerOrdersRoute: typeof OwnerOrdersRoute
  OwnerProductsRoute: typeof OwnerProductsRouteWithChildren
  OwnerProfileRoute: typeof OwnerProfileRoute
  OwnerPurchasesRoute: typeof OwnerPurchasesRoute
  OwnerRawmaterialsRoute: typeof OwnerRawmaterialsRoute
  OwnerReportsRoute: typeof OwnerReportsRoute
  OwnerRestaurantsRoute: typeof OwnerRestaurantsRouteWithChildren
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerStaffRoute: typeof OwnerStaffRouteWithChildren
  OwnerStocklogRoute: typeof OwnerStocklogRoute
  OwnerSuppliersRoute: typeof OwnerSuppliersRoute
  OwnerTablesRoute: typeof OwnerTablesRouteWithChildren
  OwnerTransactionsRoute: typeof OwnerTransactionsRoute
  OwnerUnitsRoute: typeof OwnerUnitsRoute
  OwnerUsersRoute: typeof OwnerUsersRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerCustomersIdRoute: typeof OwnerCustomersIdRoute
  OwnerExpensesIdRoute: typeof OwnerExpensesIdRoute
  OwnerNotificationsIdRoute: typeof OwnerNotificationsIdRoute
  OwnerOrdersIdRoute: typeof OwnerOrdersIdRoute
  OwnerPurchasesIdRoute: typeof OwnerPurchasesIdRoute
  OwnerRawmaterialsIdRoute: typeof OwnerRawmaterialsIdRoute
  OwnerRestaurantsRestaurantIdRoute: typeof OwnerRestaurantsRestaurantIdRoute
  OwnerStaffIdRoute: typeof OwnerStaffIdRouteWithChildren
  OwnerStocklogIdRoute: typeof OwnerStocklogIdRoute
  OwnerTablesIdRoute: typeof OwnerTablesIdRouteWithChildren
  OwnerTransactionsIdRoute: typeof OwnerTransactionsIdRoute
  OwnerLedgerPartyTypePartyIdRoute: typeof OwnerLedgerPartyTypePartyIdRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerCategoriesRoute: OwnerCategoriesRoute,
  OwnerCombosRoute: OwnerCombosRouteWithChildren,
  OwnerCustomersRoute: OwnerCustomersRoute,
  OwnerExpensesRoute: OwnerExpensesRoute,
  OwnerLedgerRoute: OwnerLedgerRoute,
  OwnerMenuQrRoute: OwnerMenuQrRoute,
  OwnerNotificationsRoute: OwnerNotificationsRoute,
  OwnerOrdersRoute: OwnerOrdersRoute,
  OwnerProductsRoute: OwnerProductsRouteWithChildren,
  OwnerProfileRoute: OwnerProfileRoute,
  OwnerPurchasesRoute: OwnerPurchasesRoute,
  OwnerRawmaterialsRoute: OwnerRawmaterialsRoute,
  OwnerReportsRoute: OwnerReportsRoute,
  OwnerRestaurantsRoute: OwnerRestaurantsRouteWithChildren,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerStaffRoute: OwnerStaffRouteWithChildren,
  OwnerStocklogRoute: OwnerStocklogRoute,
  OwnerSuppliersRoute: OwnerSuppliersRoute,
  OwnerTablesRoute: OwnerTablesRouteWithChildren,
  OwnerTransactionsRoute: OwnerTransactionsRoute,
  OwnerUnitsRoute: OwnerUnitsRoute,
  OwnerUsersRoute: OwnerUsersRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerCustomersIdRoute: OwnerCustomersIdRoute,
  OwnerExpensesIdRoute: OwnerExpensesIdRoute,
  OwnerNotificationsIdRoute: OwnerNotificationsIdRoute,
  OwnerOrdersIdRoute: OwnerOrdersIdRoute,
  OwnerPurchasesIdRoute: OwnerPurchasesIdRoute,
  OwnerRawmaterialsIdRoute: OwnerRawmaterialsIdRoute,
  OwnerRestaurantsRestaurantIdRoute: OwnerRestaurantsRestaurantIdRoute,
  OwnerStaffIdRoute: OwnerStaffIdRouteWithChildren,
  OwnerStocklogIdRoute: OwnerStocklogIdRoute,
  OwnerTablesIdRoute: OwnerTablesIdRouteWithChildren,
  OwnerTransactionsIdRoute: OwnerTransactionsIdRoute,
  OwnerLedgerPartyTypePartyIdRoute: OwnerLedgerPartyTypePartyIdRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface ShareholderRouteChildren {
  ShareholderNotificationsRoute: typeof ShareholderNotificationsRoute
  ShareholderProfileRoute: typeof ShareholderProfileRoute
  ShareholderTransactionsRoute: typeof ShareholderTransactionsRoute
  ShareholderWithdrawalsRoute: typeof ShareholderWithdrawalsRoute
  ShareholderIndexRoute: typeof ShareholderIndexRoute
  ShareholderTransactionsIdRoute: typeof ShareholderTransactionsIdRoute
}

const ShareholderRouteChildren: ShareholderRouteChildren = {
  ShareholderNotificationsRoute: ShareholderNotificationsRoute,
  ShareholderProfileRoute: ShareholderProfileRoute,
  ShareholderTransactionsRoute: ShareholderTransactionsRoute,
  ShareholderWithdrawalsRoute: ShareholderWithdrawalsRoute,
  ShareholderIndexRoute: ShareholderIndexRoute,
  ShareholderTransactionsIdRoute: ShareholderTransactionsIdRoute,
}

const ShareholderRouteWithChildren = ShareholderRoute._addFileChildren(
  ShareholderRouteChildren,
)

interface StaffRouteChildren {
  StaffCashierRoute: typeof StaffCashierRoute
  StaffExpensesRoute: typeof StaffExpensesRoute
  StaffLedgerRoute: typeof StaffLedgerRoute
  StaffLiveordersRoute: typeof StaffLiveordersRoute
  StaffMenuQrRoute: typeof StaffMenuQrRoute
  StaffNotificationsRoute: typeof StaffNotificationsRoute
  StaffPaymentAlertsRoute: typeof StaffPaymentAlertsRoute
  StaffPosRoute: typeof StaffPosRoute
  StaffProfileRoute: typeof StaffProfileRoute
  StaffPurchasesRoute: typeof StaffPurchasesRoute
  StaffTransactionsRoute: typeof StaffTransactionsRoute
  StaffWaitingPickupRoute: typeof StaffWaitingPickupRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffLedgerRestaurantIdRoute: typeof StaffLedgerRestaurantIdRoute
  StaffNotificationsIdRoute: typeof StaffNotificationsIdRoute
  StaffTransactionsIdRoute: typeof StaffTransactionsIdRoute
  StaffLedgerPartyTypePartyIdRoute: typeof StaffLedgerPartyTypePartyIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffCashierRoute: StaffCashierRoute,
  StaffExpensesRoute: StaffExpensesRoute,
  StaffLedgerRoute: StaffLedgerRoute,
  StaffLiveordersRoute: StaffLiveordersRoute,
  StaffMenuQrRoute: StaffMenuQrRoute,
  StaffNotificationsRoute: StaffNotificationsRoute,
  StaffPaymentAlertsRoute: StaffPaymentAlertsRoute,
  StaffPosRoute: StaffPosRoute,
  StaffProfileRoute: StaffProfileRoute,
  StaffPurchasesRoute: StaffPurchasesRoute,
  StaffTransactionsRoute: StaffTransactionsRoute,
  StaffWaitingPickupRoute: StaffWaitingPickupRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffLedgerRestaurantIdRoute: StaffLedgerRestaurantIdRoute,
  StaffNotificationsIdRoute: StaffNotificationsIdRoute,
  StaffTransactionsIdRoute: StaffTransactionsIdRoute,
  StaffLedgerPartyTypePartyIdRoute: StaffLedgerPartyTypePartyIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface SuperadminRouteChildren {
  SuperadminNotificationsRoute: typeof SuperadminNotificationsRoute
  SuperadminProfileRoute: typeof SuperadminProfileRoute
  SuperadminRestaurantsRoute: typeof SuperadminRestaurantsRoute
  SuperadminSettingsRoute: typeof SuperadminSettingsRoute
  SuperadminShareholdersRoute: typeof SuperadminShareholdersRoute
  SuperadminTransactionsRoute: typeof SuperadminTransactionsRoute
  SuperadminUsersRoute: typeof SuperadminUsersRoute
  SuperadminWithdrawalsRoute: typeof SuperadminWithdrawalsRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
  SuperadminNotificationsIdRoute: typeof SuperadminNotificationsIdRoute
  SuperadminRestaurantsIdRoute: typeof SuperadminRestaurantsIdRoute
  SuperadminShareholdersIdRoute: typeof SuperadminShareholdersIdRoute
  SuperadminTransactionsIdRoute: typeof SuperadminTransactionsIdRoute
  SuperadminUsersIdRoute: typeof SuperadminUsersIdRoute
  SuperadminWithdrawalsIdRoute: typeof SuperadminWithdrawalsIdRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminNotificationsRoute: SuperadminNotificationsRoute,
  SuperadminProfileRoute: SuperadminProfileRoute,
  SuperadminRestaurantsRoute: SuperadminRestaurantsRoute,
  SuperadminSettingsRoute: SuperadminSettingsRoute,
  SuperadminShareholdersRoute: SuperadminShareholdersRoute,
  SuperadminTransactionsRoute: SuperadminTransactionsRoute,
  SuperadminUsersRoute: SuperadminUsersRoute,
  SuperadminWithdrawalsRoute: SuperadminWithdrawalsRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
  SuperadminNotificationsIdRoute: SuperadminNotificationsIdRoute,
  SuperadminRestaurantsIdRoute: SuperadminRestaurantsIdRoute,
  SuperadminShareholdersIdRoute: SuperadminShareholdersIdRoute,
  SuperadminTransactionsIdRoute: SuperadminTransactionsIdRoute,
  SuperadminUsersIdRoute: SuperadminUsersIdRoute,
  SuperadminWithdrawalsIdRoute: SuperadminWithdrawalsIdRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ShareholderRoute: ShareholderRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  SuperadminRoute: SuperadminRouteWithChildren,
  WaiterMenuRoute: WaiterMenuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
